CREATE TABLE DESIGNATIONS2023 (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `DAY` int(2) DEFAULT NULL,
  `WEEK` int(2) DEFAULT NULL,
  `P_IN_WEEK` int(1) DEFAULT NULL,
  `MONTH` int(1) DEFAULT NULL,
  `PLACE` varchar(50) DEFAULT NULL,
  `TIME` char(8) DEFAULT NULL,
  `DESIGNATED_1` varchar(20) DEFAULT NULL,
  `DESIGNATED_2` varchar(20) DEFAULT NULL
)